//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.27 at 03:19:02 PM PDT 
//


package org.xml.taskdef;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoginType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoginType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="click" type="{}ClickStreamType"/>
 *         &lt;element name="redirectedURL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="loginURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gotchaURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="credential" type="{}CredentialType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoginType", propOrder = {
    "click",
    "redirectedURL",
    "loginURL",
    "gotchaURL",
    "credential"
})
public class LoginType {

    @XmlElement(required = true)
    protected ClickStreamType click;
    @XmlElement(required = true)
    protected List<String> redirectedURL;
    @XmlElement(required = true)
    protected String loginURL;
    protected String gotchaURL;
    @XmlElement(required = true)
    protected List<CredentialType> credential;

    /**
     * Gets the value of the click property.
     * 
     * @return
     *     possible object is
     *     {@link ClickStreamType }
     *     
     */
    public ClickStreamType getClick() {
        return click;
    }

    /**
     * Sets the value of the click property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClickStreamType }
     *     
     */
    public void setClick(ClickStreamType value) {
        this.click = value;
    }

    /**
     * Gets the value of the redirectedURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the redirectedURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRedirectedURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRedirectedURL() {
        if (redirectedURL == null) {
            redirectedURL = new ArrayList<String>();
        }
        return this.redirectedURL;
    }

    /**
     * Gets the value of the loginURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoginURL() {
        return loginURL;
    }

    /**
     * Sets the value of the loginURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoginURL(String value) {
        this.loginURL = value;
    }

    /**
     * Gets the value of the gotchaURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGotchaURL() {
        return gotchaURL;
    }

    /**
     * Sets the value of the gotchaURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGotchaURL(String value) {
        this.gotchaURL = value;
    }

    /**
     * Gets the value of the credential property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the credential property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCredential().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CredentialType }
     * 
     * 
     */
    public List<CredentialType> getCredential() {
        if (credential == null) {
            credential = new ArrayList<CredentialType>();
        }
        return this.credential;
    }

}
