//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.24 at 07:43:42 AM PST 
//


package org.xml.taskdef;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SplitTaskByType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SplitTaskByType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="page"/>
 *     &lt;enumeration value="item"/>
 *     &lt;enumeration value="nothing"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SplitTaskByType")
@XmlEnum
public enum SplitTaskByType {

    @XmlEnumValue("page")
    PAGE("page"),
    @XmlEnumValue("item")
    ITEM("item"),
    @XmlEnumValue("nothing")
    NOTHING("nothing");
    private final String value;

    SplitTaskByType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SplitTaskByType fromValue(String v) {
        for (SplitTaskByType c: SplitTaskByType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
