package org.cld.stock.strategy;

import java.text.SimpleDateFormat;
import java.util.Date;

public class StockOrder {
	private static SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
	public enum ActionType{
		buy,
		sell,
		sellshort,
		buycover,
		unknown
	}
	
	public enum TimeInForceType{
		DayOrder,
		GTC,
		MarktOnClose
	}
	
	public enum OrderType{
		market,
		limit,
		stop,
		stoplimit,
		stoptrailingdollar,
		stoptrailingpercentage,
		unknown
	}

	public enum StatusType{
		open,
		executed,
		partialexecuted,
		cancelled
	}
	
	private static Integer idroot=0;
	public static SimpleDateFormat detailSdf = new SimpleDateFormat("yyyyMMddhhmmssSSS");
	
	
	private String marketid;//stockbase id: sina, nasdaq
	private String orderId; //autogenerated, can't set
	private String pairOrderId;
	private Date submitTime;
	private Date executeTime;
	private Date triggerTime; //calculated by submitTime and holding duration is ss for market on close order.
	private String stockid;
	private ActionType action;
	private OrderType orderType;
	private TimeInForceType tif;
	private float limitPercentage;//the raised percentage to the corresponding executed buy order
	private float limitPrice;
	private float stopPrice;
	private int duration;//valid till number of days
	private StatusType status;
	private float executedPrice;
	private float incrementPercent;//in 1% unit
	private float incrementDollar;//in dollar unit
	private int quantity;
	
	public String toString(){
		String strExeTime = null;
		if (executeTime==null){
			strExeTime = "";
		}else{
			strExeTime = sdf.format(executeTime);
		}
		String strSubmitTime=null;
		if (submitTime==null){
			strSubmitTime="";
		}else{
			strSubmitTime = sdf.format(submitTime);
		}
		return String.format("stockid:%s, actionType:%s, orderType: %s, submitTime:%s, exePrice:%.2f, exeTime:%s", stockid, action, orderType, strSubmitTime, executedPrice, strExeTime);
	}
	public StockOrder(){
		String sd = detailSdf.format(new Date());
		synchronized(idroot){
			idroot++;
		}
		orderId = sd + "_" + idroot;
	}
	
	public String getMarketid() {
		return marketid;
	}
	public void setMarketid(String marketid) {
		this.marketid = marketid;
	}
	public String getOrderId() {
		return orderId;
	}
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}
	public Date getSubmitTime() {
		return submitTime;
	}
	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}
	public String getSymbol() {
		return stockid;
	}
	public void setSymbol(String symbol) {
		this.stockid = symbol;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public ActionType getAction() {
		return action;
	}
	public void setAction(ActionType action) {
		this.action = action;
	}
	public OrderType getOrderType() {
		return orderType;
	}
	public void setOrderType(OrderType orderType) {
		this.orderType = orderType;
	}
	public float getLimitPrice() {
		return limitPrice;
	}
	public void setLimitPrice(float limitPrice) {
		this.limitPrice = limitPrice;
	}
	public float getStopPrice() {
		return stopPrice;
	}
	public void setStopPrice(float stopPrice) {
		this.stopPrice = stopPrice;
	}
	public int getDuration() {
		return duration;
	}
	public void setDuration(int duration) {
		this.duration = duration;
	}
	public StatusType getStatus() {
		return status;
	}
	public void setStatus(StatusType status) {
		this.status = status;
	}
	public float getExecutedPrice() {
		return executedPrice;
	}
	public void setExecutedPrice(float executedPrice) {
		this.executedPrice = executedPrice;
	}
	public float getIncrementPercent() {
		return incrementPercent;
	}
	public void setIncrementPercent(float incrementPercent) {
		this.incrementPercent = incrementPercent;
	}
	public float getIncrementDollar() {
		return incrementDollar;
	}
	public void setIncrementDollar(float incrementDollar) {
		this.incrementDollar = incrementDollar;
	}
	public String getPairOrderId() {
		return pairOrderId;
	}
	public void setPairOrderId(String pairOrderId) {
		this.pairOrderId = pairOrderId;
	}
	public float getLimitPercentage() {
		return limitPercentage;
	}
	public void setLimitPercentage(float limitPercentage) {
		this.limitPercentage = limitPercentage;
	}
	public Date getExecuteTime() {
		return executeTime;
	}
	public void setExecuteTime(Date executeTime) {
		this.executeTime = executeTime;
	}
	public TimeInForceType getTif() {
		return tif;
	}
	public void setTif(TimeInForceType tif) {
		this.tif = tif;
	}
	public Date getTriggerTime() {
		return triggerTime;
	}
	public void setTriggerTime(Date triggerTime) {
		this.triggerTime = triggerTime;
	}
}
