//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.04 at 10:34:23 PM PDT 
//


package org.xml.taskdef;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CsvTransformType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CsvTransformType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outputDir" type="{}ValueType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="transformClass" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="outputType" use="required" type="{}CsvOutputType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CsvTransformType", propOrder = {
    "outputDir"
})
public class CsvTransformType {

    @XmlElement(required = true)
    protected ValueType outputDir;
    @XmlAttribute(name = "transformClass", required = true)
    protected String transformClass;
    @XmlAttribute(name = "outputType", required = true)
    protected CsvOutputType outputType;

    /**
     * Gets the value of the outputDir property.
     * 
     * @return
     *     possible object is
     *     {@link ValueType }
     *     
     */
    public ValueType getOutputDir() {
        return outputDir;
    }

    /**
     * Sets the value of the outputDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueType }
     *     
     */
    public void setOutputDir(ValueType value) {
        this.outputDir = value;
    }

    /**
     * Gets the value of the transformClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransformClass() {
        return transformClass;
    }

    /**
     * Sets the value of the transformClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransformClass(String value) {
        this.transformClass = value;
    }

    /**
     * Gets the value of the outputType property.
     * 
     * @return
     *     possible object is
     *     {@link CsvOutputType }
     *     
     */
    public CsvOutputType getOutputType() {
        return outputType;
    }

    /**
     * Sets the value of the outputType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CsvOutputType }
     *     
     */
    public void setOutputType(CsvOutputType value) {
        this.outputType = value;
    }

}
