//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.29 at 07:06:37 AM PST 
//


package org.xml.imagedata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="soundURL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="imgURL" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "entry")
public class Entry {

    @XmlAttribute(name = "soundURL", required = true)
    protected String soundURL;
    @XmlAttribute(name = "imgURL", required = true)
    protected String imgURL;

    /**
     * Gets the value of the soundURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoundURL() {
        return soundURL;
    }

    /**
     * Sets the value of the soundURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoundURL(String value) {
        this.soundURL = value;
    }

    /**
     * Gets the value of the imgURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImgURL() {
        return imgURL;
    }

    /**
     * Sets the value of the imgURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImgURL(String value) {
        this.imgURL = value;
    }

}
