//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 05:59:49 PM PST 
//


package org.xml.fixml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeskOrderHandlingInst_enum_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeskOrderHandlingInst_enum_t">
 *   &lt;restriction base="{http://www.fixprotocol.org/FIXML-5-0-SP2}MultipleStringValue">
 *     &lt;enumeration value="ADD"/>
 *     &lt;enumeration value="AON"/>
 *     &lt;enumeration value="CNH"/>
 *     &lt;enumeration value="DIR"/>
 *     &lt;enumeration value="E.W"/>
 *     &lt;enumeration value="FOK"/>
 *     &lt;enumeration value="IO"/>
 *     &lt;enumeration value="IOC"/>
 *     &lt;enumeration value="LOO"/>
 *     &lt;enumeration value="LOC"/>
 *     &lt;enumeration value="MAO"/>
 *     &lt;enumeration value="MAC"/>
 *     &lt;enumeration value="MOO"/>
 *     &lt;enumeration value="MOC"/>
 *     &lt;enumeration value="MQT"/>
 *     &lt;enumeration value="NH"/>
 *     &lt;enumeration value="OVD"/>
 *     &lt;enumeration value="PEG"/>
 *     &lt;enumeration value="RSV"/>
 *     &lt;enumeration value="S.W"/>
 *     &lt;enumeration value="SCL"/>
 *     &lt;enumeration value="TMO"/>
 *     &lt;enumeration value="TS"/>
 *     &lt;enumeration value="WRK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DeskOrderHandlingInst_enum_t")
@XmlEnum
public enum DeskOrderHandlingInstEnumT {

    ADD("ADD"),
    AON("AON"),
    CNH("CNH"),
    DIR("DIR"),
    @XmlEnumValue("E.W")
    E_W("E.W"),
    FOK("FOK"),
    IO("IO"),
    IOC("IOC"),
    LOO("LOO"),
    LOC("LOC"),
    MAO("MAO"),
    MAC("MAC"),
    MOO("MOO"),
    MOC("MOC"),
    MQT("MQT"),
    NH("NH"),
    OVD("OVD"),
    PEG("PEG"),
    RSV("RSV"),
    @XmlEnumValue("S.W")
    S_W("S.W"),
    SCL("SCL"),
    TMO("TMO"),
    TS("TS"),
    WRK("WRK");
    private final String value;

    DeskOrderHandlingInstEnumT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeskOrderHandlingInstEnumT fromValue(String v) {
        for (DeskOrderHandlingInstEnumT c: DeskOrderHandlingInstEnumT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
