//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 05:59:49 PM PST 
//


package org.xml.fixml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xml.fixml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrdMassActRpt_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "OrdMassActRpt");
    private final static QName _NewOrdMleg_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "NewOrdMleg");
    private final static QName _OrdMassActReq_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "OrdMassActReq");
    private final static QName _OrdCxlRplcReq_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "OrdCxlRplcReq");
    private final static QName _NewOrdList_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "NewOrdList");
    private final static QName _OrdMassStatReq_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "OrdMassStatReq");
    private final static QName _MlegOrdCxlRplc_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "MlegOrdCxlRplc");
    private final static QName _OrdMassCxlRpt_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "OrdMassCxlRpt");
    private final static QName _Order_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "Order");
    private final static QName _ListStat_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "ListStat");
    private final static QName _ListStatReq_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "ListStatReq");
    private final static QName _ExecAck_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "ExecAck");
    private final static QName _ListCxlReq_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "ListCxlReq");
    private final static QName _CrssOrdCxlReq_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "CrssOrdCxlReq");
    private final static QName _BidReq_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "BidReq");
    private final static QName _ListExct_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "ListExct");
    private final static QName _ListStrkPx_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "ListStrkPx");
    private final static QName _OrdMassCxlReq_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "OrdMassCxlReq");
    private final static QName _CrssOrdCxlRplcReq_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "CrssOrdCxlRplcReq");
    private final static QName _OrdStatReq_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "OrdStatReq");
    private final static QName _ExecRpt_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "ExecRpt");
    private final static QName _Message_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "Message");
    private final static QName _OrdCxlRej_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "OrdCxlRej");
    private final static QName _BidRsp_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "BidRsp");
    private final static QName _DkTrd_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "DkTrd");
    private final static QName _NewOrdCrss_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "NewOrdCrss");
    private final static QName _OrdCxlReq_QNAME = new QName("http://www.fixprotocol.org/FIXML-5-0-SP2", "OrdCxlReq");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xml.fixml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FIXML }
     * 
     */
    public FIXML createFIXML() {
        return new FIXML();
    }

    /**
     * Create an instance of {@link AbstractMessageT }
     * 
     */
    public AbstractMessageT createAbstractMessageT() {
        return new AbstractMessageT();
    }

    /**
     * Create an instance of {@link BatchT }
     * 
     */
    public BatchT createBatchT() {
        return new BatchT();
    }

    /**
     * Create an instance of {@link NewOrderSingleMessageT }
     * 
     */
    public NewOrderSingleMessageT createNewOrderSingleMessageT() {
        return new NewOrderSingleMessageT();
    }

    /**
     * Create an instance of {@link OrderMassCancelReportMessageT }
     * 
     */
    public OrderMassCancelReportMessageT createOrderMassCancelReportMessageT() {
        return new OrderMassCancelReportMessageT();
    }

    /**
     * Create an instance of {@link MultilegOrderCancelReplaceMessageT }
     * 
     */
    public MultilegOrderCancelReplaceMessageT createMultilegOrderCancelReplaceMessageT() {
        return new MultilegOrderCancelReplaceMessageT();
    }

    /**
     * Create an instance of {@link OrderMassStatusRequestMessageT }
     * 
     */
    public OrderMassStatusRequestMessageT createOrderMassStatusRequestMessageT() {
        return new OrderMassStatusRequestMessageT();
    }

    /**
     * Create an instance of {@link OrderCancelReplaceRequestMessageT }
     * 
     */
    public OrderCancelReplaceRequestMessageT createOrderCancelReplaceRequestMessageT() {
        return new OrderCancelReplaceRequestMessageT();
    }

    /**
     * Create an instance of {@link OrderMassActionRequestMessageT }
     * 
     */
    public OrderMassActionRequestMessageT createOrderMassActionRequestMessageT() {
        return new OrderMassActionRequestMessageT();
    }

    /**
     * Create an instance of {@link NewOrderMultilegMessageT }
     * 
     */
    public NewOrderMultilegMessageT createNewOrderMultilegMessageT() {
        return new NewOrderMultilegMessageT();
    }

    /**
     * Create an instance of {@link OrderMassActionReportMessageT }
     * 
     */
    public OrderMassActionReportMessageT createOrderMassActionReportMessageT() {
        return new OrderMassActionReportMessageT();
    }

    /**
     * Create an instance of {@link NewOrderListMessageT }
     * 
     */
    public NewOrderListMessageT createNewOrderListMessageT() {
        return new NewOrderListMessageT();
    }

    /**
     * Create an instance of {@link OrderCancelRejectMessageT }
     * 
     */
    public OrderCancelRejectMessageT createOrderCancelRejectMessageT() {
        return new OrderCancelRejectMessageT();
    }

    /**
     * Create an instance of {@link CrossOrderCancelReplaceRequestMessageT }
     * 
     */
    public CrossOrderCancelReplaceRequestMessageT createCrossOrderCancelReplaceRequestMessageT() {
        return new CrossOrderCancelReplaceRequestMessageT();
    }

    /**
     * Create an instance of {@link OrderStatusRequestMessageT }
     * 
     */
    public OrderStatusRequestMessageT createOrderStatusRequestMessageT() {
        return new OrderStatusRequestMessageT();
    }

    /**
     * Create an instance of {@link ExecutionReportMessageT }
     * 
     */
    public ExecutionReportMessageT createExecutionReportMessageT() {
        return new ExecutionReportMessageT();
    }

    /**
     * Create an instance of {@link OrderCancelRequestMessageT }
     * 
     */
    public OrderCancelRequestMessageT createOrderCancelRequestMessageT() {
        return new OrderCancelRequestMessageT();
    }

    /**
     * Create an instance of {@link NewOrderCrossMessageT }
     * 
     */
    public NewOrderCrossMessageT createNewOrderCrossMessageT() {
        return new NewOrderCrossMessageT();
    }

    /**
     * Create an instance of {@link DontKnowTradeMessageT }
     * 
     */
    public DontKnowTradeMessageT createDontKnowTradeMessageT() {
        return new DontKnowTradeMessageT();
    }

    /**
     * Create an instance of {@link BidResponseMessageT }
     * 
     */
    public BidResponseMessageT createBidResponseMessageT() {
        return new BidResponseMessageT();
    }

    /**
     * Create an instance of {@link ListStatusMessageT }
     * 
     */
    public ListStatusMessageT createListStatusMessageT() {
        return new ListStatusMessageT();
    }

    /**
     * Create an instance of {@link OrderMassCancelRequestMessageT }
     * 
     */
    public OrderMassCancelRequestMessageT createOrderMassCancelRequestMessageT() {
        return new OrderMassCancelRequestMessageT();
    }

    /**
     * Create an instance of {@link ListExecuteMessageT }
     * 
     */
    public ListExecuteMessageT createListExecuteMessageT() {
        return new ListExecuteMessageT();
    }

    /**
     * Create an instance of {@link ListStrikePriceMessageT }
     * 
     */
    public ListStrikePriceMessageT createListStrikePriceMessageT() {
        return new ListStrikePriceMessageT();
    }

    /**
     * Create an instance of {@link BidRequestMessageT }
     * 
     */
    public BidRequestMessageT createBidRequestMessageT() {
        return new BidRequestMessageT();
    }

    /**
     * Create an instance of {@link CrossOrderCancelRequestMessageT }
     * 
     */
    public CrossOrderCancelRequestMessageT createCrossOrderCancelRequestMessageT() {
        return new CrossOrderCancelRequestMessageT();
    }

    /**
     * Create an instance of {@link ListCancelRequestMessageT }
     * 
     */
    public ListCancelRequestMessageT createListCancelRequestMessageT() {
        return new ListCancelRequestMessageT();
    }

    /**
     * Create an instance of {@link ExecutionAcknowledgementMessageT }
     * 
     */
    public ExecutionAcknowledgementMessageT createExecutionAcknowledgementMessageT() {
        return new ExecutionAcknowledgementMessageT();
    }

    /**
     * Create an instance of {@link ListStatusRequestMessageT }
     * 
     */
    public ListStatusRequestMessageT createListStatusRequestMessageT() {
        return new ListStatusRequestMessageT();
    }

    /**
     * Create an instance of {@link DerivativeInstrumentPartiesBlockT }
     * 
     */
    public DerivativeInstrumentPartiesBlockT createDerivativeInstrumentPartiesBlockT() {
        return new DerivativeInstrumentPartiesBlockT();
    }

    /**
     * Create an instance of {@link DerivativeInstrumentPartySubIDsGrpBlockT }
     * 
     */
    public DerivativeInstrumentPartySubIDsGrpBlockT createDerivativeInstrumentPartySubIDsGrpBlockT() {
        return new DerivativeInstrumentPartySubIDsGrpBlockT();
    }

    /**
     * Create an instance of {@link StrikeRulesBlockT }
     * 
     */
    public StrikeRulesBlockT createStrikeRulesBlockT() {
        return new StrikeRulesBlockT();
    }

    /**
     * Create an instance of {@link LegBenchmarkCurveDataBlockT }
     * 
     */
    public LegBenchmarkCurveDataBlockT createLegBenchmarkCurveDataBlockT() {
        return new LegBenchmarkCurveDataBlockT();
    }

    /**
     * Create an instance of {@link TrdSessLstGrpBlockT }
     * 
     */
    public TrdSessLstGrpBlockT createTrdSessLstGrpBlockT() {
        return new TrdSessLstGrpBlockT();
    }

    /**
     * Create an instance of {@link StrategyParametersGrpBlockT }
     * 
     */
    public StrategyParametersGrpBlockT createStrategyParametersGrpBlockT() {
        return new StrategyParametersGrpBlockT();
    }

    /**
     * Create an instance of {@link InstrumentPartiesBlockT }
     * 
     */
    public InstrumentPartiesBlockT createInstrumentPartiesBlockT() {
        return new InstrumentPartiesBlockT();
    }

    /**
     * Create an instance of {@link DlvyInstGrpBlockT }
     * 
     */
    public DlvyInstGrpBlockT createDlvyInstGrpBlockT() {
        return new DlvyInstGrpBlockT();
    }

    /**
     * Create an instance of {@link ComplexEventsBlockT }
     * 
     */
    public ComplexEventsBlockT createComplexEventsBlockT() {
        return new ComplexEventsBlockT();
    }

    /**
     * Create an instance of {@link UnderlyingInstrumentBlockT }
     * 
     */
    public UnderlyingInstrumentBlockT createUnderlyingInstrumentBlockT() {
        return new UnderlyingInstrumentBlockT();
    }

    /**
     * Create an instance of {@link InstrmtMDReqGrpBlockT }
     * 
     */
    public InstrmtMDReqGrpBlockT createInstrmtMDReqGrpBlockT() {
        return new InstrmtMDReqGrpBlockT();
    }

    /**
     * Create an instance of {@link SettlDetailsBlockT }
     * 
     */
    public SettlDetailsBlockT createSettlDetailsBlockT() {
        return new SettlDetailsBlockT();
    }

    /**
     * Create an instance of {@link BaseHeaderT }
     * 
     */
    public BaseHeaderT createBaseHeaderT() {
        return new BaseHeaderT();
    }

    /**
     * Create an instance of {@link ListOrdGrpBlockT }
     * 
     */
    public ListOrdGrpBlockT createListOrdGrpBlockT() {
        return new ListOrdGrpBlockT();
    }

    /**
     * Create an instance of {@link TriggeringInstructionBlockT }
     * 
     */
    public TriggeringInstructionBlockT createTriggeringInstructionBlockT() {
        return new TriggeringInstructionBlockT();
    }

    /**
     * Create an instance of {@link InstrmtGrpBlockT }
     * 
     */
    public InstrmtGrpBlockT createInstrmtGrpBlockT() {
        return new InstrmtGrpBlockT();
    }

    /**
     * Create an instance of {@link NstdPtys2SubGrpBlockT }
     * 
     */
    public NstdPtys2SubGrpBlockT createNstdPtys2SubGrpBlockT() {
        return new NstdPtys2SubGrpBlockT();
    }

    /**
     * Create an instance of {@link MessageHeaderT }
     * 
     */
    public MessageHeaderT createMessageHeaderT() {
        return new MessageHeaderT();
    }

    /**
     * Create an instance of {@link TimeInForceRulesBlockT }
     * 
     */
    public TimeInForceRulesBlockT createTimeInForceRulesBlockT() {
        return new TimeInForceRulesBlockT();
    }

    /**
     * Create an instance of {@link ClrInstGrpBlockT }
     * 
     */
    public ClrInstGrpBlockT createClrInstGrpBlockT() {
        return new ClrInstGrpBlockT();
    }

    /**
     * Create an instance of {@link FinancingDetailsBlockT }
     * 
     */
    public FinancingDetailsBlockT createFinancingDetailsBlockT() {
        return new FinancingDetailsBlockT();
    }

    /**
     * Create an instance of {@link DerivativeEventsGrpBlockT }
     * 
     */
    public DerivativeEventsGrpBlockT createDerivativeEventsGrpBlockT() {
        return new DerivativeEventsGrpBlockT();
    }

    /**
     * Create an instance of {@link NestedInstrumentAttributeBlockT }
     * 
     */
    public NestedInstrumentAttributeBlockT createNestedInstrumentAttributeBlockT() {
        return new NestedInstrumentAttributeBlockT();
    }

    /**
     * Create an instance of {@link DiscretionInstructionsBlockT }
     * 
     */
    public DiscretionInstructionsBlockT createDiscretionInstructionsBlockT() {
        return new DiscretionInstructionsBlockT();
    }

    /**
     * Create an instance of {@link PriceLimitsBlockT }
     * 
     */
    public PriceLimitsBlockT createPriceLimitsBlockT() {
        return new PriceLimitsBlockT();
    }

    /**
     * Create an instance of {@link MiscFeesGrpBlockT }
     * 
     */
    public MiscFeesGrpBlockT createMiscFeesGrpBlockT() {
        return new MiscFeesGrpBlockT();
    }

    /**
     * Create an instance of {@link RelSymDerivSecUpdGrpBlockT }
     * 
     */
    public RelSymDerivSecUpdGrpBlockT createRelSymDerivSecUpdGrpBlockT() {
        return new RelSymDerivSecUpdGrpBlockT();
    }

    /**
     * Create an instance of {@link UndlyInstrumentPartiesBlockT }
     * 
     */
    public UndlyInstrumentPartiesBlockT createUndlyInstrumentPartiesBlockT() {
        return new UndlyInstrumentPartiesBlockT();
    }

    /**
     * Create an instance of {@link ApplicationSequenceControlBlockT }
     * 
     */
    public ApplicationSequenceControlBlockT createApplicationSequenceControlBlockT() {
        return new ApplicationSequenceControlBlockT();
    }

    /**
     * Create an instance of {@link SpreadOrBenchmarkCurveDataBlockT }
     * 
     */
    public SpreadOrBenchmarkCurveDataBlockT createSpreadOrBenchmarkCurveDataBlockT() {
        return new SpreadOrBenchmarkCurveDataBlockT();
    }

    /**
     * Create an instance of {@link PreAllocGrpBlockT }
     * 
     */
    public PreAllocGrpBlockT createPreAllocGrpBlockT() {
        return new PreAllocGrpBlockT();
    }

    /**
     * Create an instance of {@link TrdRegTimestampsBlockT }
     * 
     */
    public TrdRegTimestampsBlockT createTrdRegTimestampsBlockT() {
        return new TrdRegTimestampsBlockT();
    }

    /**
     * Create an instance of {@link SecurityXMLBlockT }
     * 
     */
    public SecurityXMLBlockT createSecurityXMLBlockT() {
        return new SecurityXMLBlockT();
    }

    /**
     * Create an instance of {@link BaseTradingRulesBlockT }
     * 
     */
    public BaseTradingRulesBlockT createBaseTradingRulesBlockT() {
        return new BaseTradingRulesBlockT();
    }

    /**
     * Create an instance of {@link NstdPtys4SubGrpBlockT }
     * 
     */
    public NstdPtys4SubGrpBlockT createNstdPtys4SubGrpBlockT() {
        return new NstdPtys4SubGrpBlockT();
    }

    /**
     * Create an instance of {@link ComplexEventTimesBlockT }
     * 
     */
    public ComplexEventTimesBlockT createComplexEventTimesBlockT() {
        return new ComplexEventTimesBlockT();
    }

    /**
     * Create an instance of {@link FillsGrpBlockT }
     * 
     */
    public FillsGrpBlockT createFillsGrpBlockT() {
        return new FillsGrpBlockT();
    }

    /**
     * Create an instance of {@link InstrmtLegExecGrpBlockT }
     * 
     */
    public InstrmtLegExecGrpBlockT createInstrmtLegExecGrpBlockT() {
        return new InstrmtLegExecGrpBlockT();
    }

    /**
     * Create an instance of {@link DisplayInstructionBlockT }
     * 
     */
    public DisplayInstructionBlockT createDisplayInstructionBlockT() {
        return new DisplayInstructionBlockT();
    }

    /**
     * Create an instance of {@link AffectedOrdGrpBlockT }
     * 
     */
    public AffectedOrdGrpBlockT createAffectedOrdGrpBlockT() {
        return new AffectedOrdGrpBlockT();
    }

    /**
     * Create an instance of {@link MaturityRulesBlockT }
     * 
     */
    public MaturityRulesBlockT createMaturityRulesBlockT() {
        return new MaturityRulesBlockT();
    }

    /**
     * Create an instance of {@link OrdAllocGrpBlockT }
     * 
     */
    public OrdAllocGrpBlockT createOrdAllocGrpBlockT() {
        return new OrdAllocGrpBlockT();
    }

    /**
     * Create an instance of {@link LegPreAllocGrpBlockT }
     * 
     */
    public LegPreAllocGrpBlockT createLegPreAllocGrpBlockT() {
        return new LegPreAllocGrpBlockT();
    }

    /**
     * Create an instance of {@link EvntGrpBlockT }
     * 
     */
    public EvntGrpBlockT createEvntGrpBlockT() {
        return new EvntGrpBlockT();
    }

    /**
     * Create an instance of {@link InstrumentExtensionBlockT }
     * 
     */
    public InstrumentExtensionBlockT createInstrumentExtensionBlockT() {
        return new InstrumentExtensionBlockT();
    }

    /**
     * Create an instance of {@link SideCrossOrdModGrpBlockT }
     * 
     */
    public SideCrossOrdModGrpBlockT createSideCrossOrdModGrpBlockT() {
        return new SideCrossOrdModGrpBlockT();
    }

    /**
     * Create an instance of {@link NestedPartiesBlockT }
     * 
     */
    public NestedPartiesBlockT createNestedPartiesBlockT() {
        return new NestedPartiesBlockT();
    }

    /**
     * Create an instance of {@link BatchHeaderT }
     * 
     */
    public BatchHeaderT createBatchHeaderT() {
        return new BatchHeaderT();
    }

    /**
     * Create an instance of {@link RootSubPartiesBlockT }
     * 
     */
    public RootSubPartiesBlockT createRootSubPartiesBlockT() {
        return new RootSubPartiesBlockT();
    }

    /**
     * Create an instance of {@link NstdPtys3SubGrpBlockT }
     * 
     */
    public NstdPtys3SubGrpBlockT createNstdPtys3SubGrpBlockT() {
        return new NstdPtys3SubGrpBlockT();
    }

    /**
     * Create an instance of {@link DerivativeInstrumentAttributeBlockT }
     * 
     */
    public DerivativeInstrumentAttributeBlockT createDerivativeInstrumentAttributeBlockT() {
        return new DerivativeInstrumentAttributeBlockT();
    }

    /**
     * Create an instance of {@link LegSecAltIDGrpBlockT }
     * 
     */
    public LegSecAltIDGrpBlockT createLegSecAltIDGrpBlockT() {
        return new LegSecAltIDGrpBlockT();
    }

    /**
     * Create an instance of {@link PositionAmountDataBlockT }
     * 
     */
    public PositionAmountDataBlockT createPositionAmountDataBlockT() {
        return new PositionAmountDataBlockT();
    }

    /**
     * Create an instance of {@link NestedParties3BlockT }
     * 
     */
    public NestedParties3BlockT createNestedParties3BlockT() {
        return new NestedParties3BlockT();
    }

    /**
     * Create an instance of {@link InstrmtLegGrpBlockT }
     * 
     */
    public InstrmtLegGrpBlockT createInstrmtLegGrpBlockT() {
        return new InstrmtLegGrpBlockT();
    }

    /**
     * Create an instance of {@link BidCompReqGrpBlockT }
     * 
     */
    public BidCompReqGrpBlockT createBidCompReqGrpBlockT() {
        return new BidCompReqGrpBlockT();
    }

    /**
     * Create an instance of {@link TargetPartiesBlockT }
     * 
     */
    public TargetPartiesBlockT createTargetPartiesBlockT() {
        return new TargetPartiesBlockT();
    }

    /**
     * Create an instance of {@link InstrumentLegBlockT }
     * 
     */
    public InstrumentLegBlockT createInstrumentLegBlockT() {
        return new InstrumentLegBlockT();
    }

    /**
     * Create an instance of {@link CompIDStatGrpBlockT }
     * 
     */
    public CompIDStatGrpBlockT createCompIDStatGrpBlockT() {
        return new CompIDStatGrpBlockT();
    }

    /**
     * Create an instance of {@link OrdTypeRulesBlockT }
     * 
     */
    public OrdTypeRulesBlockT createOrdTypeRulesBlockT() {
        return new OrdTypeRulesBlockT();
    }

    /**
     * Create an instance of {@link PtysSubGrpBlockT }
     * 
     */
    public PtysSubGrpBlockT createPtysSubGrpBlockT() {
        return new PtysSubGrpBlockT();
    }

    /**
     * Create an instance of {@link NestedParties4BlockT }
     * 
     */
    public NestedParties4BlockT createNestedParties4BlockT() {
        return new NestedParties4BlockT();
    }

    /**
     * Create an instance of {@link ComplexEventDatesBlockT }
     * 
     */
    public ComplexEventDatesBlockT createComplexEventDatesBlockT() {
        return new ComplexEventDatesBlockT();
    }

    /**
     * Create an instance of {@link DerivativeSecurityDefinitionBlockT }
     * 
     */
    public DerivativeSecurityDefinitionBlockT createDerivativeSecurityDefinitionBlockT() {
        return new DerivativeSecurityDefinitionBlockT();
    }

    /**
     * Create an instance of {@link TrdgSesGrpBlockT }
     * 
     */
    public TrdgSesGrpBlockT createTrdgSesGrpBlockT() {
        return new TrdgSesGrpBlockT();
    }

    /**
     * Create an instance of {@link SideCrossOrdCxlGrpBlockT }
     * 
     */
    public SideCrossOrdCxlGrpBlockT createSideCrossOrdCxlGrpBlockT() {
        return new SideCrossOrdCxlGrpBlockT();
    }

    /**
     * Create an instance of {@link CommissionDataBlockT }
     * 
     */
    public CommissionDataBlockT createCommissionDataBlockT() {
        return new CommissionDataBlockT();
    }

    /**
     * Create an instance of {@link RoutingGrpBlockT }
     * 
     */
    public RoutingGrpBlockT createRoutingGrpBlockT() {
        return new RoutingGrpBlockT();
    }

    /**
     * Create an instance of {@link LinesOfTextGrpBlockT }
     * 
     */
    public LinesOfTextGrpBlockT createLinesOfTextGrpBlockT() {
        return new LinesOfTextGrpBlockT();
    }

    /**
     * Create an instance of {@link SettlPartiesBlockT }
     * 
     */
    public SettlPartiesBlockT createSettlPartiesBlockT() {
        return new SettlPartiesBlockT();
    }

    /**
     * Create an instance of {@link MatchRulesBlockT }
     * 
     */
    public MatchRulesBlockT createMatchRulesBlockT() {
        return new MatchRulesBlockT();
    }

    /**
     * Create an instance of {@link PartiesBlockT }
     * 
     */
    public PartiesBlockT createPartiesBlockT() {
        return new PartiesBlockT();
    }

    /**
     * Create an instance of {@link MsgTypeGrpBlockT }
     * 
     */
    public MsgTypeGrpBlockT createMsgTypeGrpBlockT() {
        return new MsgTypeGrpBlockT();
    }

    /**
     * Create an instance of {@link RateSourceBlockT }
     * 
     */
    public RateSourceBlockT createRateSourceBlockT() {
        return new RateSourceBlockT();
    }

    /**
     * Create an instance of {@link InstrmtLegSecListGrpBlockT }
     * 
     */
    public InstrmtLegSecListGrpBlockT createInstrmtLegSecListGrpBlockT() {
        return new InstrmtLegSecListGrpBlockT();
    }

    /**
     * Create an instance of {@link CompIDReqGrpBlockT }
     * 
     */
    public CompIDReqGrpBlockT createCompIDReqGrpBlockT() {
        return new CompIDReqGrpBlockT();
    }

    /**
     * Create an instance of {@link ContraGrpBlockT }
     * 
     */
    public ContraGrpBlockT createContraGrpBlockT() {
        return new ContraGrpBlockT();
    }

    /**
     * Create an instance of {@link SettlPtysSubGrpBlockT }
     * 
     */
    public SettlPtysSubGrpBlockT createSettlPtysSubGrpBlockT() {
        return new SettlPtysSubGrpBlockT();
    }

    /**
     * Create an instance of {@link NestedParties2BlockT }
     * 
     */
    public NestedParties2BlockT createNestedParties2BlockT() {
        return new NestedParties2BlockT();
    }

    /**
     * Create an instance of {@link UndlyInstrumentPtysSubGrpBlockT }
     * 
     */
    public UndlyInstrumentPtysSubGrpBlockT createUndlyInstrumentPtysSubGrpBlockT() {
        return new UndlyInstrumentPtysSubGrpBlockT();
    }

    /**
     * Create an instance of {@link TradingSessionRulesBlockT }
     * 
     */
    public TradingSessionRulesBlockT createTradingSessionRulesBlockT() {
        return new TradingSessionRulesBlockT();
    }

    /**
     * Create an instance of {@link InstrumentBlockT }
     * 
     */
    public InstrumentBlockT createInstrumentBlockT() {
        return new InstrumentBlockT();
    }

    /**
     * Create an instance of {@link YieldDataBlockT }
     * 
     */
    public YieldDataBlockT createYieldDataBlockT() {
        return new YieldDataBlockT();
    }

    /**
     * Create an instance of {@link PegInstructionsBlockT }
     * 
     */
    public PegInstructionsBlockT createPegInstructionsBlockT() {
        return new PegInstructionsBlockT();
    }

    /**
     * Create an instance of {@link InstrmtLegIOIGrpBlockT }
     * 
     */
    public InstrmtLegIOIGrpBlockT createInstrmtLegIOIGrpBlockT() {
        return new InstrmtLegIOIGrpBlockT();
    }

    /**
     * Create an instance of {@link LegOrdGrpBlockT }
     * 
     */
    public LegOrdGrpBlockT createLegOrdGrpBlockT() {
        return new LegOrdGrpBlockT();
    }

    /**
     * Create an instance of {@link UnderlyingStipulationsBlockT }
     * 
     */
    public UnderlyingStipulationsBlockT createUnderlyingStipulationsBlockT() {
        return new UnderlyingStipulationsBlockT();
    }

    /**
     * Create an instance of {@link BidDescReqGrpBlockT }
     * 
     */
    public BidDescReqGrpBlockT createBidDescReqGrpBlockT() {
        return new BidDescReqGrpBlockT();
    }

    /**
     * Create an instance of {@link NstdPtysSubGrpBlockT }
     * 
     */
    public NstdPtysSubGrpBlockT createNstdPtysSubGrpBlockT() {
        return new NstdPtysSubGrpBlockT();
    }

    /**
     * Create an instance of {@link UndSecAltIDGrpBlockT }
     * 
     */
    public UndSecAltIDGrpBlockT createUndSecAltIDGrpBlockT() {
        return new UndSecAltIDGrpBlockT();
    }

    /**
     * Create an instance of {@link DerivativeInstrumentBlockT }
     * 
     */
    public DerivativeInstrumentBlockT createDerivativeInstrumentBlockT() {
        return new DerivativeInstrumentBlockT();
    }

    /**
     * Create an instance of {@link TradingSessionRulesGrpBlockT }
     * 
     */
    public TradingSessionRulesGrpBlockT createTradingSessionRulesGrpBlockT() {
        return new TradingSessionRulesGrpBlockT();
    }

    /**
     * Create an instance of {@link InstrumentPtysSubGrpBlockT }
     * 
     */
    public InstrumentPtysSubGrpBlockT createInstrumentPtysSubGrpBlockT() {
        return new InstrumentPtysSubGrpBlockT();
    }

    /**
     * Create an instance of {@link OrderQtyDataBlockT }
     * 
     */
    public OrderQtyDataBlockT createOrderQtyDataBlockT() {
        return new OrderQtyDataBlockT();
    }

    /**
     * Create an instance of {@link StipulationsBlockT }
     * 
     */
    public StipulationsBlockT createStipulationsBlockT() {
        return new StipulationsBlockT();
    }

    /**
     * Create an instance of {@link MarketSegmentGrpBlockT }
     * 
     */
    public MarketSegmentGrpBlockT createMarketSegmentGrpBlockT() {
        return new MarketSegmentGrpBlockT();
    }

    /**
     * Create an instance of {@link PreAllocMlegGrpBlockT }
     * 
     */
    public PreAllocMlegGrpBlockT createPreAllocMlegGrpBlockT() {
        return new PreAllocMlegGrpBlockT();
    }

    /**
     * Create an instance of {@link HopGrpBlockT }
     * 
     */
    public HopGrpBlockT createHopGrpBlockT() {
        return new HopGrpBlockT();
    }

    /**
     * Create an instance of {@link OrdListStatGrpBlockT }
     * 
     */
    public OrdListStatGrpBlockT createOrdListStatGrpBlockT() {
        return new OrdListStatGrpBlockT();
    }

    /**
     * Create an instance of {@link SettlInstructionsDataBlockT }
     * 
     */
    public SettlInstructionsDataBlockT createSettlInstructionsDataBlockT() {
        return new SettlInstructionsDataBlockT();
    }

    /**
     * Create an instance of {@link NotAffectedOrdersGrpBlockT }
     * 
     */
    public NotAffectedOrdersGrpBlockT createNotAffectedOrdersGrpBlockT() {
        return new NotAffectedOrdersGrpBlockT();
    }

    /**
     * Create an instance of {@link LotTypeRulesBlockT }
     * 
     */
    public LotTypeRulesBlockT createLotTypeRulesBlockT() {
        return new LotTypeRulesBlockT();
    }

    /**
     * Create an instance of {@link SecondaryPriceLimitsBlockT }
     * 
     */
    public SecondaryPriceLimitsBlockT createSecondaryPriceLimitsBlockT() {
        return new SecondaryPriceLimitsBlockT();
    }

    /**
     * Create an instance of {@link LegStipulationsBlockT }
     * 
     */
    public LegStipulationsBlockT createLegStipulationsBlockT() {
        return new LegStipulationsBlockT();
    }

    /**
     * Create an instance of {@link TickRulesBlockT }
     * 
     */
    public TickRulesBlockT createTickRulesBlockT() {
        return new TickRulesBlockT();
    }

    /**
     * Create an instance of {@link DerivativeSecurityXMLBlockT }
     * 
     */
    public DerivativeSecurityXMLBlockT createDerivativeSecurityXMLBlockT() {
        return new DerivativeSecurityXMLBlockT();
    }

    /**
     * Create an instance of {@link SecAltIDGrpBlockT }
     * 
     */
    public SecAltIDGrpBlockT createSecAltIDGrpBlockT() {
        return new SecAltIDGrpBlockT();
    }

    /**
     * Create an instance of {@link MarketDataFeedTypesBlockT }
     * 
     */
    public MarketDataFeedTypesBlockT createMarketDataFeedTypesBlockT() {
        return new MarketDataFeedTypesBlockT();
    }

    /**
     * Create an instance of {@link SecurityTradingRulesBlockT }
     * 
     */
    public SecurityTradingRulesBlockT createSecurityTradingRulesBlockT() {
        return new SecurityTradingRulesBlockT();
    }

    /**
     * Create an instance of {@link PositionQtyBlockT }
     * 
     */
    public PositionQtyBlockT createPositionQtyBlockT() {
        return new PositionQtyBlockT();
    }

    /**
     * Create an instance of {@link BidCompRspGrpBlockT }
     * 
     */
    public BidCompRspGrpBlockT createBidCompRspGrpBlockT() {
        return new BidCompRspGrpBlockT();
    }

    /**
     * Create an instance of {@link InstrmtStrkPxGrpBlockT }
     * 
     */
    public InstrmtStrkPxGrpBlockT createInstrmtStrkPxGrpBlockT() {
        return new InstrmtStrkPxGrpBlockT();
    }

    /**
     * Create an instance of {@link ContAmtGrpBlockT }
     * 
     */
    public ContAmtGrpBlockT createContAmtGrpBlockT() {
        return new ContAmtGrpBlockT();
    }

    /**
     * Create an instance of {@link RootPartiesBlockT }
     * 
     */
    public RootPartiesBlockT createRootPartiesBlockT() {
        return new RootPartiesBlockT();
    }

    /**
     * Create an instance of {@link ExecInstRulesBlockT }
     * 
     */
    public ExecInstRulesBlockT createExecInstRulesBlockT() {
        return new ExecInstRulesBlockT();
    }

    /**
     * Create an instance of {@link AttrbGrpBlockT }
     * 
     */
    public AttrbGrpBlockT createAttrbGrpBlockT() {
        return new AttrbGrpBlockT();
    }

    /**
     * Create an instance of {@link UndInstrmtGrpBlockT }
     * 
     */
    public UndInstrmtGrpBlockT createUndInstrmtGrpBlockT() {
        return new UndInstrmtGrpBlockT();
    }

    /**
     * Create an instance of {@link DerivativeSecurityAltIDGrpBlockT }
     * 
     */
    public DerivativeSecurityAltIDGrpBlockT createDerivativeSecurityAltIDGrpBlockT() {
        return new DerivativeSecurityAltIDGrpBlockT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderMassActionReportMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "OrdMassActRpt", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<OrderMassActionReportMessageT> createOrdMassActRpt(OrderMassActionReportMessageT value) {
        return new JAXBElement<OrderMassActionReportMessageT>(_OrdMassActRpt_QNAME, OrderMassActionReportMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewOrderMultilegMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "NewOrdMleg", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<NewOrderMultilegMessageT> createNewOrdMleg(NewOrderMultilegMessageT value) {
        return new JAXBElement<NewOrderMultilegMessageT>(_NewOrdMleg_QNAME, NewOrderMultilegMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderMassActionRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "OrdMassActReq", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<OrderMassActionRequestMessageT> createOrdMassActReq(OrderMassActionRequestMessageT value) {
        return new JAXBElement<OrderMassActionRequestMessageT>(_OrdMassActReq_QNAME, OrderMassActionRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderCancelReplaceRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "OrdCxlRplcReq", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<OrderCancelReplaceRequestMessageT> createOrdCxlRplcReq(OrderCancelReplaceRequestMessageT value) {
        return new JAXBElement<OrderCancelReplaceRequestMessageT>(_OrdCxlRplcReq_QNAME, OrderCancelReplaceRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewOrderListMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "NewOrdList", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<NewOrderListMessageT> createNewOrdList(NewOrderListMessageT value) {
        return new JAXBElement<NewOrderListMessageT>(_NewOrdList_QNAME, NewOrderListMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderMassStatusRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "OrdMassStatReq", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<OrderMassStatusRequestMessageT> createOrdMassStatReq(OrderMassStatusRequestMessageT value) {
        return new JAXBElement<OrderMassStatusRequestMessageT>(_OrdMassStatReq_QNAME, OrderMassStatusRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultilegOrderCancelReplaceMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "MlegOrdCxlRplc", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<MultilegOrderCancelReplaceMessageT> createMlegOrdCxlRplc(MultilegOrderCancelReplaceMessageT value) {
        return new JAXBElement<MultilegOrderCancelReplaceMessageT>(_MlegOrdCxlRplc_QNAME, MultilegOrderCancelReplaceMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderMassCancelReportMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "OrdMassCxlRpt", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<OrderMassCancelReportMessageT> createOrdMassCxlRpt(OrderMassCancelReportMessageT value) {
        return new JAXBElement<OrderMassCancelReportMessageT>(_OrdMassCxlRpt_QNAME, OrderMassCancelReportMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewOrderSingleMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "Order", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<NewOrderSingleMessageT> createOrder(NewOrderSingleMessageT value) {
        return new JAXBElement<NewOrderSingleMessageT>(_Order_QNAME, NewOrderSingleMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListStatusMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "ListStat", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<ListStatusMessageT> createListStat(ListStatusMessageT value) {
        return new JAXBElement<ListStatusMessageT>(_ListStat_QNAME, ListStatusMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListStatusRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "ListStatReq", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<ListStatusRequestMessageT> createListStatReq(ListStatusRequestMessageT value) {
        return new JAXBElement<ListStatusRequestMessageT>(_ListStatReq_QNAME, ListStatusRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExecutionAcknowledgementMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "ExecAck", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<ExecutionAcknowledgementMessageT> createExecAck(ExecutionAcknowledgementMessageT value) {
        return new JAXBElement<ExecutionAcknowledgementMessageT>(_ExecAck_QNAME, ExecutionAcknowledgementMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListCancelRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "ListCxlReq", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<ListCancelRequestMessageT> createListCxlReq(ListCancelRequestMessageT value) {
        return new JAXBElement<ListCancelRequestMessageT>(_ListCxlReq_QNAME, ListCancelRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrossOrderCancelRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "CrssOrdCxlReq", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<CrossOrderCancelRequestMessageT> createCrssOrdCxlReq(CrossOrderCancelRequestMessageT value) {
        return new JAXBElement<CrossOrderCancelRequestMessageT>(_CrssOrdCxlReq_QNAME, CrossOrderCancelRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BidRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "BidReq", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<BidRequestMessageT> createBidReq(BidRequestMessageT value) {
        return new JAXBElement<BidRequestMessageT>(_BidReq_QNAME, BidRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListExecuteMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "ListExct", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<ListExecuteMessageT> createListExct(ListExecuteMessageT value) {
        return new JAXBElement<ListExecuteMessageT>(_ListExct_QNAME, ListExecuteMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListStrikePriceMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "ListStrkPx", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<ListStrikePriceMessageT> createListStrkPx(ListStrikePriceMessageT value) {
        return new JAXBElement<ListStrikePriceMessageT>(_ListStrkPx_QNAME, ListStrikePriceMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderMassCancelRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "OrdMassCxlReq", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<OrderMassCancelRequestMessageT> createOrdMassCxlReq(OrderMassCancelRequestMessageT value) {
        return new JAXBElement<OrderMassCancelRequestMessageT>(_OrdMassCxlReq_QNAME, OrderMassCancelRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrossOrderCancelReplaceRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "CrssOrdCxlRplcReq", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<CrossOrderCancelReplaceRequestMessageT> createCrssOrdCxlRplcReq(CrossOrderCancelReplaceRequestMessageT value) {
        return new JAXBElement<CrossOrderCancelReplaceRequestMessageT>(_CrssOrdCxlRplcReq_QNAME, CrossOrderCancelReplaceRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderStatusRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "OrdStatReq", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<OrderStatusRequestMessageT> createOrdStatReq(OrderStatusRequestMessageT value) {
        return new JAXBElement<OrderStatusRequestMessageT>(_OrdStatReq_QNAME, OrderStatusRequestMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExecutionReportMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "ExecRpt", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<ExecutionReportMessageT> createExecRpt(ExecutionReportMessageT value) {
        return new JAXBElement<ExecutionReportMessageT>(_ExecRpt_QNAME, ExecutionReportMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "Message")
    public JAXBElement<AbstractMessageT> createMessage(AbstractMessageT value) {
        return new JAXBElement<AbstractMessageT>(_Message_QNAME, AbstractMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderCancelRejectMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "OrdCxlRej", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<OrderCancelRejectMessageT> createOrdCxlRej(OrderCancelRejectMessageT value) {
        return new JAXBElement<OrderCancelRejectMessageT>(_OrdCxlRej_QNAME, OrderCancelRejectMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BidResponseMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "BidRsp", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<BidResponseMessageT> createBidRsp(BidResponseMessageT value) {
        return new JAXBElement<BidResponseMessageT>(_BidRsp_QNAME, BidResponseMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DontKnowTradeMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "DkTrd", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<DontKnowTradeMessageT> createDkTrd(DontKnowTradeMessageT value) {
        return new JAXBElement<DontKnowTradeMessageT>(_DkTrd_QNAME, DontKnowTradeMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NewOrderCrossMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "NewOrdCrss", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<NewOrderCrossMessageT> createNewOrdCrss(NewOrderCrossMessageT value) {
        return new JAXBElement<NewOrderCrossMessageT>(_NewOrdCrss_QNAME, NewOrderCrossMessageT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderCancelRequestMessageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", name = "OrdCxlReq", substitutionHeadNamespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", substitutionHeadName = "Message")
    public JAXBElement<OrderCancelRequestMessageT> createOrdCxlReq(OrderCancelRequestMessageT value) {
        return new JAXBElement<OrderCancelRequestMessageT>(_OrdCxlReq_QNAME, OrderCancelRequestMessageT.class, null, value);
    }

}
