//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.04 at 05:59:49 PM PST 
//

@XmlSchema(
		namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", 
		elementFormDefault = XmlNsForm.UNQUALIFIED)
package org.xml.fixml;

import javax.xml.bind.annotation.*;
