--NasdaqFrQuarterBalanceSheet
drop table if exists NasdaqFrQuarterBalanceSheet;
create external table NasdaqFrQuarterBalanceSheet(stockid String, quarter String, reportPeriod Date, cash decimal(20,2), shortTermInvestment decimal(20,2), NetReceivables decimal(20,2), OtherCurrentAssets decimal(20,2), totalCurrentAssets decimal(20,2), longTermInvestment decimal(20,2), fixedAssets decimal(20,2), goodwill decimal(20,2), intangibleAssets decimal(20,2), otherAssets decimal(20,2), deferredAssetChanges decimal(20,2), totalAssets decimal(20,2), accountsPayable decimal(20,2), shortTermDebt decimal(20,2), otherCurrentLiabilities decimal(20,2), totalCurrentLiabilities decimal(20,2), longTermDebt decimal(20,2), otherLiabilities decimal(20,2), deferredLiabilityCharges decimal(20,2), miscStocks decimal(20,2), minorityInterest decimal(20,2), totalLiabilities decimal(20,2), commonStock decimal(20,2), capitalSurplus decimal(20,2), retainedEarnings decimal(20,2), treasuryStock decimal(20,2), otherEquity decimal(20,2), totalEquity decimal(20,2), totalLiabilityEquity decimal(20,2)) row format delimited fields terminated by ',' escaped by '\\' stored as textfile location '/reminder/items/merge/nasdaq-fr-quarter-BalanceSheet';

--NasdaqFrQuarterCashFlow
drop table if exists NasdaqFrQuarterCashFlow;
create external table NasdaqFrQuarterCashFlow(stockid String, quarter String, reportPeriod Date, NetIncome decimal(20,2), depreciation decimal(20,2), netIncomeAdjustments decimal(20,2), accountsReceibles decimal(20,2), changesInventory decimal(20,2), otherOperatingActivities decimal(20,2), liabilities decimal(20,2), netCashFlowsOperating decimal(20,2), capitalExpenditures decimal(20,2), investments decimal(20,2), otherInvestingActivities decimal(20,2), netCashFlowsInvesting decimal(20,2), saleAndPurchaseOfStock decimal(20,2), netBorrowings decimal(20,2), otherFinancialActivities decimal(20,2), netCashFlowsFinancing decimal(20,2), effectOfExchangeRate decimal(20,2), netCashFlow decimal(20,2)) row format delimited fields terminated by ',' escaped by '\\' stored as textfile location '/reminder/items/merge/nasdaq-fr-quarter-CashFlow';

--nasdaq-fr-quarter-IncomeStatement
drop table if exists NasdaqFrQuarterIncomeStatement;
create external table NasdaqFrQuarterIncomeStatement(stockid String, quarter String, reportPeriod Date, totalRevenue decimal(20,2), costOfRevenue decimal(20,2), grossProfit decimal(20,2), randd decimal(20,2), salesGeneralAdmin decimal(20,2), nonRecurringItems decimal(20,2), otherOperationgItems decimal(20,2), OperatingIncome decimal(20,2), AdditionalIncomeExpenseItems decimal(20,2), earningBeforeInterestTax decimal(20,2), interestExpense decimal(20,2), earningBeforeTax decimal(20,2), incomeTax decimal(20,2), minorityInterest decimal(20,2), equityEarningLossUnconsolidatedSubsidary decimal(20,2), netIncomeContOperations decimal(20,2), netIncome decimal(20,2), netIncomeToShareHolder decimal(20,2)) row format delimited fields terminated by ',' escaped by '\\' stored as textfile location '/reminder/items/merge/nasdaq-fr-quarter-IncomeStatement';

