drop table if exists tc;
create table if not exists tc (
	mid string,
	tid string
);

--tradable entity basic info
drop table if exists tcbi;
create table if not exists tcbi (
	mid string comment 'market id unchangable',
	tid string comment 'stock id on the market unchangable',
	pid date comment 'period id',
	
	name string comment '公司法定中文名称',
	legalrep string comment '公司法定代表人',
	companyaddr string comment '公司注册地址',
	zipcode string comment '公司办公地址邮政编码',
	website string comment '网址',
	bsname string comment '董事会秘书姓名',
	bsphone string comment '董事会秘书电话',
	bsemail string comment '董事会秘书电子信箱',
	
	stockholdernum int comment '报告期末股东总数',
	numberbonussharepertenshare float comment '每10股送红股数',
	dividentpertenshare float comment '每10股派息数',
	numbershareconvertedbycaptitalreservepertenshare float comment '每10股转增数',
	revenuethisperiod float comment '本期营业收入',
	profitthisperiod float comment '本期营业利润',
	profitthisyear float comment '利润总额',
	profitbelongstockholder float comment '归属于上市公司股东的净利润',
	profitshn float comment '归属于上市公司股东的扣除非经常性损益的净利润',
	cashflow float comment '经营活动产生的现金流量净额',
	totalCapital float comment '总资产',
	equityStakeHolder float comment '所有者权益',
	basicEarningPerShare float comment '基本每股收益',
	DilutedEarningPerShare float comment '稀释每股收益',
	BasicEpsNetOfNonRecurringGainsAndLosses float comment '扣除非经常性损益后的基本每股收益',
	FullyDilutedReturnOnEquityRatio float comment '全面摊薄净资产收益率',
	WeightedAverageReturnOnEquityRatio float comment '加权平均净资产收益率',
	FullyDilutedReturnOnEquityNetOfNonRecurringGainsAndLossesRatio float comment '扣除非经常性损益后全面摊薄净资产收益率',
	weightedAverageReturnOnEquityNetOfNonRecurringGainsAndLossesRatio float comment '扣除非经常性损益后的加权平均净资产收益率',
	netCashFlowsPerShareFromOperatingActivities float comment '每股经营活动产生的现金流量净额',
	netAssetsPerShareAttributableToShareholdersOfListedCompany float comment '归属于上市公司股东的每股净资产',
	--股本结构
	NumberOfStateOwnedFloatingSharesWithTradingLimitedConditions bigint comment '国家持有的有限售条件流通股份数',
	NumberOfFloatingSharesWithTradingLimitedConditionsHeldByStateLegalEntity bigint comment '国有法人持有的有限售条件流通股份数',
	NumberOfFloatingSharesWithTradingLimitedConditionsHeldByDomesticCapital bigint comment '其他有限售条件的内资流通股份数',
	NumberOfFloatingSharesWithTradingLimitedConditionsHeldByDomesticLegalEntity bigint comment '境内法人持有的有限售条件流通股份数',
	NumberOfFloatingSharesWithTradingLimitedConditionsHeldByDomesticNaturalPerson bigint comment '境内自然人持有的有限售条件流通股份数',
	NumberOfFloatingSharesWithTradingLimitedConditionsHeldByForeignCapital bigint comment '有限售条件的外资流通股份数',
	NumberOfFloatingSharesWithTradingLimitedConditionsHeldByForeignLegalEntity bigint comment '境外法人持有的有限售条件流通股份数',
	NumberOfFloatingSharesWithTradingLimitedConditionsHeldByForeignNaturalPerson bigint comment '境外自然人持有的有限售条件流通股份数',
	NumberOfFloatingSharesWithOtherTradingLimitedConditions bigint comment '其他有限售股流通股数',
	NumberOfFloatingSharesWithTradingLimitedConditions bigint comment '有限售条件流通股数',
	NumberOfCommonFloatingSharesRMBDenominatedWithoutTradingLimitedConditions bigint comment '无限售条件人民币普通股数',
	NumberOfDomesticallyListedSharesWithoutTradingLimitedConditionsHeldByForeignInvestors bigint comment '无限售条件境内上市的外资股数',
	NumberOfOverseasListedSharesWithoutTradingLimitedConditionsHeldByForeignInvestors bigint comment '无限售条件境外上市的外资股数',
	NumberOfOtherListedMarketableSharesWithoutTradingLimitedConditions bigint comment '其他无限售条件已上市流通股份数',
	SubTotalOfFloatingSharesWithoutTradingLimitedConditions bigint comment '无限售条件流通股份合计',
	TotalShares bigint comment '股份总数',
	--another 16 ratio is omitted
	--资产负债表
	monetaryFunds float comment '货币资金',
	transactionSettlementFunds float comment '结算备付金',
	loansToOtherBank  float comment '拆出资金',
	tradingFinancialAssets float comment '交易性金融资产',
	notesReceivable  float comment '应收票据',
	accountsReceivable float comment '应收帐款',
	accountsInAdvance float comment '预付帐款',
	insurancePremiumReceivable float comment '应收保费',
	reinsurancePremiumReceivable  float comment '应收分保账款',
	reserveReinsuranceContractReceivable float comment '应收分保合同准备金',
	interestReceivable float comment '应收利息',
	dividentReceivable float comment '应收股利',
	otherReceivable float comment '其他应收款',
	BuyInAndReturnToAndSellFinancialAssets float comment '买入返售金融资产',
	inventories float comment '库存',
	nonCurrentAssetsExpireInAYear float comment '一年内到期的非流动资产',
	otherCurrentAssets float comment '其他流动资产',
	SubTotalOfCurrentAssets float comment '流动资产合计',
	DisbursementOfAdvancesAndLoans float comment '发放贷款和垫款',
	AvailableForSaleFinancialAssets float comment '可供出售金融资产',
	HeldToMaturityInvestment float comment '持有至到期投资',
	LongTermAccountsReceivable float comment '长期应收款',
	LongTermEquityInvestment float comment '长期股权投资',
	InvestmentRealEstates float comment '投资性房地产',
	FixedAssetsNet float comment '固定资产净额',
	ConstructionInProgress float comment '在建工程',
	ConstructionMaterials float comment '工程物资',
	DisposalOfFixedAssets float comment '固定资产清理',
	capitalizedBiologicalAssets float comment '生产性生物资产',
	OilAndGasAssets float comment '油气资产',
	IntangibleAssets float comment '无形资产',
	RAndDExpenses float comment '开发支出',
	goodwill float comment '商誉',
	LongTermDeferredAndPrepaidExpenses float comment '长期待摊费用',
	TotalDeferredTaxesDebitItem  float comment '递延税款借项合计',
	OtherLongTermAssets float comment '其他长期资产',
	TotalNonCurrentAssets float comment '非流动资产合计',
	TotalAssets float comment '资产总计',
	ShortTermLoans float comment '短期借款',
	BorrowingsFromCentralBank float comment '向中央银行借款',
	ReceiptOfDepositsAndDepositsFromOtherBanks  float comment '吸收存款及同业存放',
	LoansFromOtherBanks float comment '拆入资金',
	TradingFinancialLiabilities float comment '交易性金融负债',
	NotesPayable float comment '应付票据',
	AccountsPayable float comment '应付帐款',
	AccountsReceivedInAdvance float comment '预收帐款',
	FundsFromSellingOutAndRepurchasingFinancialAssets float comment '卖出回购金融资产款',
	FeesAndCommissionsPayable float comment '应付手续费及佣金',
	EmployeeCompensationPayable float comment '应付职工薪酬',
	TaxesPayable float comment '应交税金',
	InterestsPayable  float comment '应付利息',
	DividentsPayable float comment '应付股利',
	OtherPayable float comment '其他应付款',
	ReinsuredAccountsPayable float comment '应付分保账款',
	ReservesForInsurance float comment '保险合同准备金',
	FundsFromSecuritiesTradingAgency float comment '代理买卖证券款',
	FundsFromUnderwritingSecuritiesAgency float comment '代理承销证券款',
	LongTermLiabilitiesDueWithinOneYear float comment '一年内到期的长期负债',
	OtherCurrentLiabilities float comment '其他流动负债',
	SubTotalOfCurrentLiabilities float comment '流动负债合计',
	LongTermLoans float comment '长期借款',
	BondsPayable float comment '应付债券',
	LongTermPayable float comment '长期应付款',
	SpecialPayables float comment '专项应付款',
	EstimatedLiabilities float comment '预计负债',
	TotalDeferredTaxesCreditItem float comment '递延税款贷项合计',
	OtherLongTermLiabilities float comment '其他长期负债',
	liabilityLongTermTotal float comment '长期负债合计',
	liabilitytotal float comment '负债合计',
	capitalpaidin float comment '股本',
	capitalreserve float comment '资本公积',
	stocktreasury float comment '库存股',
	reservesurplus float comment '盈余公积',
	reserveordinaryrisk float comment '一般风险准备',
	profitundistributed float comment '未分配利润',
	capitalforeigncorrency float comment '外币报表折算差额',
	equityattribtoparentcompanytotal float comment 'Total equity attributable to the parent company owners 归属于母公司所有者权益合计',
	interestsminority float comment 'Minority Interests 少数股东权益',
	equitytotalshareholders float comment '股东权益合计',
	totalliabilityshareholderequity float comment 'Total Liabilities And Shareholders Equity 负债和股东权益合计',
	--利润表
	revenuetotal float comment '营业总收入',
	revenue float comment '营业收入',
	incomefinancialassetinterest float comment '金融资产利息收入',
	earnedinsurancepremium float comment '已赚保费',
	feesandcommissionincome float comment '手续费及佣金收入',
	totaloperatingcost float comment '营业总成本',
	operatingcost float comment '营业成本',
	financialassetinterstexpense float comment '金融资产利息支出',
	feesandcommissionexpense float comment '手续费及佣金支出',
	refundedpremium float comment '退保金',
	netamountcompensationpayout float comment '赔付支出净额',
	netamountreservereinsurancecontract float comment '提取保险合同准备金净额',
	policydividendpayment float comment '保单红利支出',
	reinsuredexpense float comment '分保费用',
	businesstaxextra float comment '营业税金及附加',
	salesexpense float comment '销售费用',
	managementexpense float comment '管理费用',
	financeexpense float comment '财务费用',
	assetsimpairementloss float comment '资产减值损失',
	incomeschangeinfairvalue float comment '公允价值变动收益',
	investmentincome float comment '投资收益',
	investmentincomejointventurepartnership float comment '对联营企业和合营企业的投资收益',
	foreignexchangeincome float comment '汇兑收益',
	operateprofit float comment '营业利润',
	nonoperatingrevenue float comment '营业外收入',
	nonoperatingexpenditure float comment '营业外支出',
	netlossdisposalofnoncurrentassets float comment '非流动资产处置净损失',
	incomebeforetax float comment '利润总额',
	incometax float comment '所得税',
	netprofit float comment '净利润',
	netprofitattributabletoparentcompany float comment '归属于母公司所有者的净利润',
	minorityshareholderincome float comment '少数股东损益',
	basiceps float comment '基本每股收益',
	dilutedeps float comment '稀释每股收益',
	--现金流量表
	CashReceivedFromSellingCommoditiesAndProvidingLaborServices float comment '销售商品提供劳务收到的现金',
	NetIncreaseOfDepositsFromCustomersAndOtherBanks float comment '客户存款和同业存放款项净增加额',
	NetIncreaseOfBorrowingsFromCentralBank float comment '向中央银行借款净增加额',
	NetIncreaseOfLoansFromOtherFinancialInstitutions float comment '向其他金融机构拆入资金净增加额',
	CashReceivedFromReceivingInsurancePremiumOfOriginalInsuranceContract float comment '收到原保险合同保费取得的现金',
	NetCashReceivedFromReinsuranceBusiness float comment '收到再保险业务现金净额',
	NetIncreaseOfPolicyHolderDepositsAndInvestmentFunds float comment '保户储金及投资款净增加额',
	NetIncreaseOfDisposalOfTradingFinancialAssets float comment '处置交易性金融资产净增加额',
	CashReceivedFromInterestsFeesAndCommissions float comment '收取利息,手续费及佣金的现金',
	NetIncreaseOfLoansFromOtherBanks float comment '拆入资金净增加额',
	NetCapitalIncreaseOfRepurchaseBusiness float comment '回购业务资金净增加额',
	RefundsOfTaxesAndLevies float comment '收到的税费返还',
	ItemsOfOtherReceivedCashRelevantToOperatingActivities float comment '收到的其他与经营活动有关的现金',
	SubTotalOfCashInflowsFromOperatingActivities float comment '经营活动现金流入小计',
	CashPaidForPurchasingCommoditiesAndReceivingLaborService float comment '购买商品接受劳务支付的现金',
	NetIncreaseOfCustomerLoansAndAdvances float comment '客户贷款及垫款净增加额',
	NetIncreaseOfDepositsInCentralBankAndOtherBanks float comment '存放中央银行和同业款项净增加额',
	CashPaidForIndemnityOfOriginalInsuranceContract float comment '支付原保险合同赔付款项的现金',
	CashPaidForInterestsFeesAndCommissions float comment '支付利息,手续费及佣金的现金',
	CashPaidForPolicyDividends float comment '支付保单红利的现金',
	CashPaidToAndOnBehalfOfEmployees float comment '支付给职工以及为职工支付的现金',
	CashPaidForTaxes float comment '支付的各项税费',
	CashPaidRelatingToOtherOperatingActivities float comment '支付的其他与经营活动有关的现金',
	SubTotalOfCashOutflowsFromOperatingActivities float comment '经营活动现金流出小计',
	NetCashFlowsArisingFromOperatingActivities float comment '经营活动现金流量净额',
	CashReceivedFromSalesOfInvestments float comment '收回投资所收到的现金',
	CashReceivedFromReturnOnInvestments float comment '取得投资收益所收到的现金',
	NetCashReceivedFromDisposalOfFixedAssetsIntangibleAssetsAndOtherLongTermAssets float comment '处置固定资产,无形资产和其他长期资产而收回的现金',
	IncludingCashReceivedFromSalesOfSubsidiaries float comment '收回投资所收到的现金中的出售子公司收到的现金',
	ItemsOfOtherReceivedCashRelevantToInvestingActivities float comment '收到的其他与投资活动有关的现金',
	SubTotalOfCashInflowsFromInvestingActivities float comment '投资活动现金流入小计',
	CashPaidToAcquireFixedAssetsIntangibleAssetsAndOtherLongTermAssets float comment '购建固定资产、无形资产和其他长期资产所支付的现金',
	CashPaidToInvestments float comment '投资所支付的现金',
	NetIncreaseOfPledgeLoans float comment '质押贷款净增加额',
	NetCashReceivedFromPaymentOfSubsidiariesAndOtherBusinessUnits float comment '取得子公司及其他营业单位支付的现金净额',
	OtherCashPaidRelatingToInvestingActivities float comment '支付的其他与投资活动有关的现金',
	SubTotalOfCashOutflowsFromInvestingActivities float comment '投资活动现金流出小计',
	NetCashFlowsFromInvestingActivities float comment '投资活动产生的现金流量净额',
	ProceedsFromIssuingStocksAndBonds float comment '吸收投资所收到的现金',
	CashReceivedFromSubsidiaryCompanyAbsorbedInvestmentOfMinorityShareholdersEquity float comment '吸收投资所收到的现金中的子公司吸收少数股东权益性投资收到的现金',
	ProceedsFromBorrowings float comment '借款所收到的现金',
	CashReceivedFromIssuingBonds float comment '发行债券所收到的现金',
	ProceedsReceivedFromOtherFinancingActivities float comment '收到其他与筹资活动有关的现金',
	SubTotalOfCashInflowsFromFinancingActivities float comment '筹资活动现金流入小计',
	RepaymentOfBorrowings float comment '偿还债务所支付的现金',
	CashPaidForDistributingDividendsAndProfitsOrPayingInterests float comment '分配股利利润或偿付利息所支付的现金',
	DividendsOfMinorityShareholdersPaidBySubsidiaryCompany float comment '分配股利利润或偿付利息所支付的现金中的支付少数股东的股利',
	OtherPaidCashRelevantToFinancingActivities float comment '支付的其他与筹资活动有关的现金',
	SubTotalOfCashOutflowsFromFinancingActivities float comment '筹资活动现金流出小计',
	NetCashFlowsFromFinancingActivities float comment '筹资活动产生的现金流量净额',
	InfluenceOfFluctuationInExchangeRateOnCash float comment '汇率变动对现金的影响',
	NetIncreaseInCashAndCashEquivalents float comment '现金及现金等价物净增加额',
	CashAndCashEquivalents float comment '现金及现金等价物余额'
);

drop table if exists topstockholder;
create table if not exists topstockholder (
	mid string,
	tid string,
	pid string,
	name string,
	volume bigint,
	percent float,
	rank smallint
);
