//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.22 at 03:44:23 AM PST 
//


package org.xml.fixml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}Message"/>
 *         &lt;element name="Batch" type="{http://www.fixprotocol.org/FIXML-5-0-SP2}Batch_t" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{http://www.fixprotocol.org/FIXML-5-0-SP2}FixmlAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "message",
    "batch"
})
@XmlRootElement(name = "FIXML")
public class FIXML {

    @XmlElementRef(name = "Message", namespace = "http://www.fixprotocol.org/FIXML-5-0-SP2", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends AbstractMessageT> message;
    @XmlElement(name = "Batch")
    protected List<BatchT> batch;
    @XmlAttribute(name = "v")
    protected String v;
    @XmlAttribute(name = "r")
    protected String r;
    @XmlAttribute(name = "xv")
    protected Integer xv;
    @XmlAttribute(name = "cv")
    protected String cv;
    @XmlAttribute(name = "xr")
    protected String xr;
    @XmlAttribute(name = "s")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar s;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link OrderMassStatusRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link BidRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link NewOrderMultilegMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link CrossOrderCancelReplaceRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link BidResponseMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ListStatusMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderCancelRejectMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ListCancelRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderCancelRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link NewOrderSingleMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link NewOrderListMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link CrossOrderCancelRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ListExecuteMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderMassActionReportMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ExecutionReportMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ListStrikePriceMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link MultilegOrderCancelReplaceMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link NewOrderCrossMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ExecutionAcknowledgementMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderMassActionRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link DontKnowTradeMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderMassCancelReportMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ListStatusRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderMassCancelRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderCancelReplaceRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderStatusRequestMessageT }{@code >}
     *     
     */
    public JAXBElement<? extends AbstractMessageT> getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link OrderMassStatusRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link BidRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link NewOrderMultilegMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link CrossOrderCancelReplaceRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link BidResponseMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ListStatusMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderCancelRejectMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ListCancelRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderCancelRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link NewOrderSingleMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link NewOrderListMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link CrossOrderCancelRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ListExecuteMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderMassActionReportMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ExecutionReportMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ListStrikePriceMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link MultilegOrderCancelReplaceMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link NewOrderCrossMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ExecutionAcknowledgementMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderMassActionRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link DontKnowTradeMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderMassCancelReportMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link ListStatusRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderMassCancelRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderCancelReplaceRequestMessageT }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrderStatusRequestMessageT }{@code >}
     *     
     */
    public void setMessage(JAXBElement<? extends AbstractMessageT> value) {
        this.message = value;
    }

    /**
     * Gets the value of the batch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the batch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BatchT }
     * 
     * 
     */
    public List<BatchT> getBatch() {
        if (batch == null) {
            batch = new ArrayList<BatchT>();
        }
        return this.batch;
    }

    /**
     * Gets the value of the v property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getV() {
        if (v == null) {
            return "FIX.5.0SP2";
        } else {
            return v;
        }
    }

    /**
     * Sets the value of the v property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setV(String value) {
        this.v = value;
    }

    /**
     * Gets the value of the r property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getR() {
        return r;
    }

    /**
     * Sets the value of the r property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setR(String value) {
        this.r = value;
    }

    /**
     * Gets the value of the xv property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getXv() {
        return xv;
    }

    /**
     * Sets the value of the xv property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setXv(Integer value) {
        this.xv = value;
    }

    /**
     * Gets the value of the cv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCv() {
        return cv;
    }

    /**
     * Sets the value of the cv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCv(String value) {
        this.cv = value;
    }

    /**
     * Gets the value of the xr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXr() {
        return xr;
    }

    /**
     * Sets the value of the xr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXr(String value) {
        this.xr = value;
    }

    /**
     * Gets the value of the s property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getS() {
        return s;
    }

    /**
     * Sets the value of the s property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setS(XMLGregorianCalendar value) {
        this.s = value;
    }

}
